feat: add call on extension
enzymefinance/sdk pull request #30
Opened 2023-04-19 13:37 UTC by KedziaPawel

## PR-Codex overview
This PR adds new functions and types related to integrations, updates enums and constants, and adds new tests. 

### Detailed summary
- Adds `createTestRevert` function to `error.ts`.
- Adds `LEND_SELECTOR` and `REDEEM_SELECTOR` constants to `selectors.ts`.
- Adds `IntegrationManagerActionId` and `Integration` enums to `enums.ts`.
- Adds `CallArgsForIntegration` type and `encodeCallArgsForIntegration` and `decodeCallArgsForIntegration` functions to `callArgs.ts`.
- Adds `IntegrationDataForAaveV2Lend`, `CallArgsForAaveV2Lend`, `AaveV2LendTrade`, `encodeIntegrationDataForAaveV2Lend`, `decodeIntegrationDataForAaveV2Lend`, `encodeCallArgsForAaveV2Lend`, `decodeCallArgsForAaveV2Lend`, `prepareCallOnAaveV2LendParams`, `IntegrationDataForAaveV2Redeem`, `CallArgsForAaveV2Redeem`, `AaveV2RedeemTrade`, `encodeIntegrationDataForAaveV2Redeem`, `decodeIntegrationDataForAaveV2Redeem`, `encodeCallArgsForAaveV2Redeem`, `decodeCallArgsForAaveV2Redeem`, and `prepareCallOnAaveV2RedeemParams` functions to `aaveV2.ts`.
- Adds `PrepareTradeParams` type and `prepareAdapterTrade` function to `prepareAdapterTrade.ts`.
- Updates `VaultAction`, `RateAsset`, `FeeType`, and `FeeAmount` enums in `enums.ts`.
- Adds `FEE_MANAGER`, `INTEGRATION_MANAGER`, and `AAVE_V2_ADAPTER` constants to `constants.ts`.
- Adds new tests to various files.

> The following files were skipped due to too many changes: `packages/sdk/src/actions/claimOwnership.test.ts`, `packages/sdk/src/actions/buyShares.test.ts`, `packages/sdk/src/actions/redeemSharesInKind.test.ts`, `packages/sdk/src/actions/prepareAdapterTrade.test.ts`, `packages/sdk/src/integrations/callArgs.test.ts`, `packages/sdk/src/actions/redeemSharesForSpecificAssets.test.ts`, `packages/sdk/src/integrations/aaveV2.ts`, `packages/sdk/src/errors/getErrorCode.ts`, `packages/sdk/src/integrations/aaveV2.test.ts`, `packages/sdk/reverts.txt`, `packages/sdk/src/errors/errors.test.ts`, `packages/sdk/src/errors/errorCodes.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-04-19 13:40 UTC, fubhy requested changes

2023-04-19 13:40 UTC, fubhy commented on packages/sdk/src/actions/callOnExtension.test.ts
> +  ]);
Can we also get utils for this? So end users wouldn't have to write this themselves?

2023-04-19 13:40 UTC, fubhy commented on packages/sdk/tests/constants.ts
> +export const A_WETH = "0x030bA81f1c18d280636F32af80b9AAd02Cf0854e"; //
What's that comment?

2023-04-20 06:30 UTC, rayphelan commented on packages/sdk/src/integrations/aaveV2.ts
> +export function encodeIntegrationDataForAaveV2Lend({ aToken, depositAmount }: IntegrationDataForAaveV2Lend) {
You could add the `Hex` return type to this function

2023-04-26 15:07 UTC, fubhy requested changes

2023-04-26 15:07 UTC, fubhy commented on packages/sdk/src/errors/errorCodes.ts
> +    description: "Policies and settingsData array lengths unequal",
We can also accept it as this for now and revisit all these description in one go at some point with a native speaker?

2023-04-26 15:07 UTC, fubhy commented on packages/sdk/src/constants/selectors.ts
> +export const REDEEM_SELECTOR = getFunctionSelector("redeem(address,bytes,bytes)");
Let's avoid function calls in `constants.ts`. Please copy& paste the result of the function call here. And add a comment afterwards.

2023-04-26 15:07 UTC, fubhy commented on packages/sdk/tests/error.ts
> +}
`createTestRevert`

2023-04-26 15:07 UTC, fubhy commented on packages/sdk/src/errors/errors.test.ts
> +});
You can use `test.each` for this.

2023-04-26 16:19 UTC, merged